[package]
name = "envl-cli"
version = "0.1.0"
description = "envl's cli"
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
proc-macro = true

[[bin]]
name = "envl"
path = "src/cli.rs"

[dependencies]
envl = { path = "../envl-rs" }
envl-config = { path = "../envl-config"}
envl-vars = { path = "../envl-vars" }
envl-utils = { path = "../envl-utils" }
proc-macro2 = { version = "1.0.101" }
quote = { version = "1.0.40" }
syn = { version = "2.0.106", features = ["full", "extra-traits"] }
serde = { version = "1", features = ["derive"] }
serde_json = { version = "1" }
clap = { version = "4.5.46", features = ["derive"] }

[lints]
workspace = true
