[workspace]
resolver = "3"
members = [
    "packages/envl-rs",
    "packages/envl-cli",
    "packages/envl-config",
    "packages/envl-vars",
    "packages/envl-utils",
    "tests/envl-rs-test"
]

[workspace.package]
repository = "https://github.com/ROBOTofficial/envl"
license = "MIT"
edition = "2021"
rust-version = "1.75"

[patch.crates-io]
envl = { path = "packages/envl-rs" }
envl-vars = { path = "packages/envl-vars" }
envl-config = { path = "packages/envl-config" }
envl-utils = { path = "packages/envl-utils" }

[workspace.lints.clippy]
