[package]
name = "envl-vars"
version = "0.1.0"
description = "parser and lexer for .envl file."
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["rlib", "cdylib", "staticlib"]

[dependencies]
