[package]
name = "envl"
version = "0.1.0"
description = "load .envl and .envlconf"
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
crate-type = ["rlib", "cdylib"]

[dependencies]
tokio = { version = "1.47.1", features = ["full"] }
envl-config = { path = "../envl-config" }
envl-vars = { path = "../envl-vars" }
envl-utils = { path = "../envl-utils" }
