[package]
name = "envl"
version = "0.6.0"
description = "load .envl and .envlconf"
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]

[dependencies]
tokio = { version = "1.47.1", features = ["full"] }
envl-config = { version = "0.3.0" }
envl-vars = { version = "1.1.0" }
envl-utils = { version = "0.2.0" }
proc-macro2 = { version = "1.0.101" }
quote = { version = "1.0.40" }
syn = { version = "2.0.106", features = ["full", "extra-traits"] }
