[package]
name = "envl"
version.workspace = true
description = "load .envl and .envlconf"
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]

[dependencies]
tokio = { version = "1.47.1", features = ["full"] }
envl-config.workspace = true
envl-vars.workspace = true
envl-utils.workspace = true
proc-macro2 = { version = "1.0.101" }
quote = { version = "1.0.41" }
syn = { version = "2.0.106", features = ["full", "extra-traits"] }
