[package]
name = "envl-utils"
version = "0.2.0"
description = "util elements for envl"
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]

[lints]
workspace = true
