[package]
name = "envl-config"
version = "0.3.0"
description = "parser and lexer for .envlconf file."
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]

[dependencies]
envl-utils = { version = "0.2.0" }
thiserror.workspace = true
