[package]
name = "envl-config"
version.workspace = true
description = "parser and lexer for .envlconf file."
repository.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]

[dependencies]
envl-utils.workspace = true
thiserror.workspace = true
